export const COUNTRIES_IT = [
  { value: "AF", label: "AF - Afghanistan" },
  { value: "AL", label: "AL - Albania" },
  { value: "DZ", label: "DZ - Algeria" },
  { value: "AD", label: "AD - Andorra" },
  { value: "AO", label: "AO - Angola" },
  { value: "AG", label: "AG - Antigua e Barbuda" },
  { value: "SA", label: "SA - Arabia Saudita" },
  { value: "AR", label: "AR - Argentina" },
  { value: "AM", label: "AM - Armenia" },
  { value: "AU", label: "AU - Australia" },
  { value: "AT", label: "AT - Austria" },
  { value: "AZ", label: "AZ - Azerbaigian" },
  { value: "BS", label: "BS - Bahamas" },
  { value: "BH", label: "BH - Bahrein" },
  { value: "BD", label: "BD - Bangladesh" },
  { value: "BB", label: "BB - Barbados" },
  { value: "BE", label: "BE - Belgio" },
  { value: "BZ", label: "BZ - Belize" },
  { value: "BJ", label: "BJ - Benin" },
  { value: "BY", label: "BY - Bielorussia" },
  { value: "BO", label: "BO - Bolivia" },
  { value: "BA", label: "BA - Bosnia ed Erzegovina" },
  { value: "BW", label: "BW - Botswana" },
  { value: "BR", label: "BR - Brasile" },
  { value: "BN", label: "BN - Brunei" },
  { value: "BG", label: "BG - Bulgaria" },
  { value: "BF", label: "BF - Burkina Faso" },
  { value: "BI", label: "BI - Burundi" },
  { value: "KH", label: "KH - Cambogia" },
  { value: "CM", label: "CM - Camerun" },
  { value: "CA", label: "CA - Canada" },
  { value: "CV", label: "CV - Capo Verde" },
  { value: "CF", label: "CF - Repubblica Centrafricana" },
  { value: "TD", label: "TD - Ciad" },
  { value: "CL", label: "CL - Cile" },
  { value: "CN", label: "CN - Cina" },
  { value: "CY", label: "CY - Cipro" },
  { value: "VA", label: "VA - Città del Vaticano" },
  { value: "CO", label: "CO - Colombia" },
  { value: "KM", label: "KM - Comore" },
  { value: "CG", label: "CG - Congo" },
  { value: "CD", label: "CD - Congo (Rep. Dem.)" },
  { value: "KP", label: "KP - Corea del Nord" },
  { value: "KR", label: "KR - Corea del Sud" },
  { value: "CR", label: "CR - Costa Rica" },
  { value: "HR", label: "HR - Croazia" },
  { value: "CU", label: "CU - Cuba" },
  { value: "DK", label: "DK - Danimarca" },
  { value: "DO", label: "DO - Repubblica Dominicana" },
  { value: "EC", label: "EC - Ecuador" },
  { value: "EG", label: "EG - Egitto" },
  { value: "SV", label: "SV - El Salvador" },
  { value: "AE", label: "AE - Emirati Arabi Uniti" },
  { value: "ER", label: "ER - Eritrea" },
  { value: "EE", label: "EE - Estonia" },
  { value: "ET", label: "ET - Etiopia" },
  { value: "SZ", label: "SZ - Eswatini" },
  { value: "PH", label: "PH - Filippine" },
  { value: "FI", label: "FI - Finlandia" },
  { value: "FJ", label: "FJ - Figi" },
  { value: "FR", label: "FR - Francia" },
  { value: "GA", label: "GA - Gabon" },
  { value: "GM", label: "GM - Gambia" },
  { value: "GE", label: "GE - Georgia" },
  { value: "DE", label: "DE - Germania" },
  { value: "GH", label: "GH - Ghana" },
  { value: "JM", label: "JM - Giamaica" },
  { value: "JP", label: "JP - Giappone" },
  { value: "DJ", label: "DJ - Gibuti" },
  { value: "JO", label: "JO - Giordania" },
  { value: "GR", label: "GR - Grecia" },
  { value: "GD", label: "GD - Grenada" },
  { value: "GT", label: "GT - Guatemala" },
  { value: "GN", label: "GN - Guinea" },
  { value: "GQ", label: "GQ - Guinea Equatoriale" },
  { value: "GW", label: "GW - Guinea-Bissau" },
  { value: "GY", label: "GY - Guyana" },
  { value: "HT", label: "HT - Haiti" },
  { value: "HN", label: "HN - Honduras" },
  { value: "IN", label: "IN - India" },
  { value: "ID", label: "ID - Indonesia" },
  { value: "IR", label: "IR - Iran" },
  { value: "IQ", label: "IQ - Iraq" },
  { value: "IE", label: "IE - Irlanda" },
  { value: "IS", label: "IS - Islanda" },
  { value: "MH", label: "MH - Isole Marshall" },
  { value: "SB", label: "SB - Isole Salomone" },
  { value: "IL", label: "IL - Israele" },
  { value: "IT", label: "IT - Italia" },
  { value: "KZ", label: "KZ - Kazakistan" },
  { value: "KE", label: "KE - Kenya" },
  { value: "KG", label: "KG - Kirghizistan" },
  { value: "KI", label: "KI - Kiribati" },
  { value: "XK", label: "XK - Kosovo" },
  { value: "KW", label: "KW - Kuwait" },
  { value: "LA", label: "LA - Laos" },
  { value: "LS", label: "LS - Lesotho" },
  { value: "LV", label: "LV - Lettonia" },
  { value: "LB", label: "LB - Libano" },
  { value: "LR", label: "LR - Liberia" },
  { value: "LY", label: "LY - Libia" },
  { value: "LI", label: "LI - Liechtenstein" },
  { value: "LT", label: "LT - Lituania" },
  { value: "LU", label: "LU - Lussemburgo" },
  { value: "MK", label: "MK - Macedonia del Nord" },
  { value: "MG", label: "MG - Madagascar" },
  { value: "MW", label: "MW - Malawi" },
  { value: "MY", label: "MY - Malaysia" },
  { value: "MV", label: "MV - Maldive" },
  { value: "ML", label: "ML - Mali" },
  { value: "MT", label: "MT - Malta" },
  { value: "MA", label: "MA - Marocco" },
  { value: "MR", label: "MR - Mauritania" },
  { value: "MU", label: "MU - Mauritius" },
  { value: "MX", label: "MX - Messico" },
  { value: "FM", label: "FM - Micronesia" },
  { value: "MD", label: "MD - Moldavia" },
  { value: "MC", label: "MC - Monaco" },
  { value: "MN", label: "MN - Mongolia" },
  { value: "ME", label: "ME - Montenegro" },
  { value: "MZ", label: "MZ - Mozambico" },
  { value: "MM", label: "MM - Myanmar" },
  { value: "NA", label: "NA - Namibia" },
  { value: "NR", label: "NR - Nauru" },
  { value: "NP", label: "NP - Nepal" },
  { value: "NI", label: "NI - Nicaragua" },
  { value: "NE", label: "NE - Niger" },
  { value: "NG", label: "NG - Nigeria" },
  { value: "NO", label: "NO - Norvegia" },
  { value: "NZ", label: "NZ - Nuova Zelanda" },
  { value: "OM", label: "OM - Oman" },
  { value: "NL", label: "NL - Paesi Bassi" },
  { value: "PK", label: "PK - Pakistan" },
  { value: "PW", label: "PW - Palau" },
  { value: "PS", label: "PS - Palestina" },
  { value: "PA", label: "PA - Panama" },
  { value: "PG", label: "PG - Papua Nuova Guinea" },
  { value: "PY", label: "PY - Paraguay" },
  { value: "PE", label: "PE - Perù" },
  { value: "PL", label: "PL - Polonia" },
  { value: "PT", label: "PT - Portogallo" },
  { value: "QA", label: "QA - Qatar" },
  { value: "GB", label: "GB - Regno Unito" },
  { value: "CZ", label: "CZ - Repubblica Ceca" },
  { value: "RO", label: "RO - Romania" },
  { value: "RU", label: "RU - Russia" },
  { value: "RW", label: "RW - Ruanda" },
  { value: "KN", label: "KN - Saint Kitts e Nevis" },
  { value: "LC", label: "LC - Saint Lucia" },
  { value: "VC", label: "VC - Saint Vincent e Grenadine" },
  { value: "WS", label: "WS - Samoa" },
  { value: "SM", label: "SM - San Marino" },
  { value: "ST", label: "ST - São Tomé e Príncipe" },
  { value: "SN", label: "SN - Senegal" },
  { value: "RS", label: "RS - Serbia" },
  { value: "SC", label: "SC - Seychelles" },
  { value: "SL", label: "SL - Sierra Leone" },
  { value: "SG", label: "SG - Singapore" },
  { value: "SY", label: "SY - Siria" },
  { value: "SK", label: "SK - Slovacchia" },
  { value: "SI", label: "SI - Slovenia" },
  { value: "SO", label: "SO - Somalia" },
  { value: "ES", label: "ES - Spagna" },
  { value: "LK", label: "LK - Sri Lanka" },
  { value: "SD", label: "SD - Sudan" },
  { value: "SS", label: "SS - Sudan del Sud" },
  { value: "SR", label: "SR - Suriname" },
  { value: "SE", label: "SE - Svezia" },
  { value: "CH", label: "CH - Svizzera" },
  { value: "TW", label: "TW - Taiwan" },
  { value: "TJ", label: "TJ - Tagikistan" },
  { value: "TH", label: "TH - Tailandia" },
  { value: "TZ", label: "TZ - Tanzania" },
  { value: "TL", label: "TL - Timor-Leste" },
  { value: "TG", label: "TG - Togo" },
  { value: "TO", label: "TO - Tonga" },
  { value: "TT", label: "TT - Trinidad e Tobago" },
  { value: "TN", label: "TN - Tunisia" },
  { value: "TR", label: "TR - Turchia" },
  { value: "TM", label: "TM - Turkmenistan" },
  { value: "TV", label: "TV - Tuvalu" },
  { value: "UA", label: "UA - Ucraina" },
  { value: "UG", label: "UG - Uganda" },
  { value: "HU", label: "HU - Ungheria" },
  { value: "UY", label: "UY - Uruguay" },
  { value: "UZ", label: "UZ - Uzbekistan" },
  { value: "VU", label: "VU - Vanuatu" },
  { value: "VE", label: "VE - Venezuela" },
  { value: "VN", label: "VN - Vietnam" },
  { value: "YE", label: "YE - Yemen" },
  { value: "ZM", label: "ZM - Zambia" },
  { value: "ZW", label: "ZW - Zimbabwe" },
];
